apiVersion: v1
appVersion: V1.0
description: 'De Producten en Diensten Catalogus heeft als doel het geheel aan af te nemen producten en/of diensten in kaart te brengen. Hierbij wordt uitgegaan van afname door klanten vanuit een organisatie, maar er is geen technische beperking om het ook als inkoopsysteem te gebruiken. Naast producten en diensten kent het component ook ondersteuning voor het maken van productgroepen, beschrijvende teksten, afbeeldingen, belastingen en andere zaken die specifiek gerelateerd zijn aan webshop concepten. Hierbij wordt (vanuit internationale normen) een onderscheid gemaakt tussen het product en het aanbieden van het product (offer) waarbij het mogelijk is om een aanbod te koppelen aan geldigheid of doelgroepen. Met andere woorden het is mogelijk om een product op bepaalde momenten goedkoper of juist duurder aan te bieden (trouwen in het weekend) of goedkoper aan te bieden voor bepaalde doelgroepen (korting op evenementen vergunningen voor buurtcomités).'
name: productenendienstencatalogus
version: 0.1.0
home: https://www.conduction.nl
icon: https://conductionnl.github.io/images/conduction_avatar_blue_on_transparant.svg
sources:
    - https://commonground.conduction.nl/
    - https://www.commonground.nl/
keywords:
    - commonground
    - haven
    - nlx
    - component
maintainers:
    - email: ruben@conduction.nl
      name: Ruben van der Linde
    - email: info@conduction.nl
      name: Conduction
dependencies:
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.1.1
      condition: postgresql.enabled
