apiVersion: v1
entries:
  pdc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-09-17T13:44:39.7502786Z"
    description: '&#039;This component provides a products and services catalogue
      that can be used by a order component in order to provide the products in the
      orders with better details. The design considerations are given in [DESIGN.md](https://github.com/ConductionNL/productenendienstencatalogus/blob/master/DESIGN.md)
      and [DESIGN-PDC.md](https://github.com/ConductionNL/productenendienstencatalogus/blob/master/DESIGN-PDC.md)&#039;'
    digest: 4751321c9e76152187586eca9a61e865bdaaf31960ae1223738138c95109f50c
    home: pdc.zuid-drecht.nl
    icon: pdc.zuid-drecht.nl
    name: pdc
    urls:
    - pdc-0.1.0.tgz
    version: 0.1.0
generated: "2020-09-17T13:44:39.7369628Z"
