apiVersion: v1
entries:
  pc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-09-09T06:45:54.1703481Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: a3ebf537582710b118b706a276db61fec8e25b642f3e8f3d1bb239ac1131f064
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: pc
    urls:
    - pc-0.1.0.tgz
    version: 0.1.0
  pdc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-09-09T06:45:54.174864Z"
    description: This component provides a products and services catalogue that can
      be used by a order component in order to provide the products in the orders
      with better details. The design considerations are given in [DESIGN.md](https://github.com/ConductionNL/productenendienstencatalogus/blob/master/DESIGN.md)
      and [DESIGN-PDC.md](https://github.com/ConductionNL/productenendienstencatalogus/blob/master/DESIGN-PDC.md)
    digest: 051c378306215b9188e14fa50c436f4603f01c0847c9a712cad07a1ad2403040
    home: pdc.zuid-drecht.nl
    icon: pdc.zuid-drecht.nl
    name: pdc
    urls:
    - pdc-0.1.0.tgz
    version: 0.1.0
generated: "2020-09-09T06:45:54.165635Z"
