apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "name" . }}-php
  labels:
    app.kubernetes.io/name: {{ include "name" . }}-php
    app.kubernetes.io/part-of: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "name" . }}-php
        app.kubernetes.io/part-of: {{ include "name" . }}
        helm.sh/chart: {{ include "chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ include "name" . }}-php
          image: "{{ .Values.settings.registryBase }}/pdc-php:{{ .Values.settings.env }}"
          imagePullPolicy: {{ .Values.settings.pullPolicy }}
          ports:
            - containerPort: 9000
          env:
            - name: JWT_SECRET_KEY
              value: '%kernel.project_dir%/config/jwt/private.pem'
            - name: JWT_PUBLIC_KEY
              value: '%kernel.project_dir%/config/jwt/public.pem'
            - name: JWT_PASSPHRASE
              value: 'bafe1dc254b45471754c221081f874aa' #@todo this should be a variable
            - name: TRUSTED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: trusted-hosts
            - name: TRUSTED_PROXIES
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: trusted-proxies
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: app-name
            - name: APP_TITLE
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: app-title
            - name: APP_DESCRIPTION
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: app-description
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: app-version
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: env
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: debug
            - name: APP_DEMO
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: app-demo
            - name: APP_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: app-domain
            # organization
            - name: ORGANIZATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: organization-name
            - name: ORGANIZATION_EMAIL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: organization-email
            - name: ORGANIZATION_COUNTRY_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: organization-country
            - name: ORGANIZATION_STATE
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: organization-state
            - name: ORGANIZATION_LOCALITY
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: organization-locality
            - name: ORGANIZATION_UNIT_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: organization-unit
            # config
            - name: AUTH_ENABLED
              value: "false"
            - name: AUDITTRAIL_ENABLED
              value: "false"
            - name: NOTIFICATION_ENABLED
              value: "false"
            - name: HEALTH_ENABLED
              value: "false"
            - name: ARCHIVE_ENABLED
              value: "false"
            
            # bla bla      
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: cors-allow-origin
            - name: VARNISH_URL
              value: {{ include "name" . }}-varnish
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: database-url
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
