name: Pull Request Test

on:
    push:
        branches:
            - master
jobs:
    create_pr:
        runs-on: ubuntu-latest
        name: Create Pull-Request on child repositories
        #needs: build
        if: contains( github.ref, 'master' )
        steps:
            - uses: actions/checkout@v1
            - name: Install hub
              uses: geertvdc/setup-hub@master
            - name: Create PR
              run: hub pull-request -b GemeenteUtrecht/productenendienstencatalogus:master -h ConductionNL/productenendienstencatalogus:master -m "Automated pull request from GitHub Action"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_USER: ${{ github.actor }}
